### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by naphtap** [gprezza/DASH_rRNA_depletion#1]
Hello, 
I gave the script a try with a manual bed file, following all the instructions on the page. However, when I run the script, I get the following error:
Traceback (most recent call last):
  File "design_grnas.py", line 198, in <module>
    PAM_list = remove_ambiguous(PAM)
  File "design_grnas.py", line 46, in remove_ambiguous
    d = Seq.IUPAC.IUPACData.ambiguous_dna_values
AttributeError: module 'Bio.Seq' has no attribute 'IUPAC'

I ran the following command on my working directory:
python3 design_grnas.py -o --manual_ann annotations/P749_rRNA.bed 

I also have Bio, primer3-py, and Bowtie installed.

I also made a custom bed file according to the instructions in the readme, but I don't think that's the problem.

Thank you.

**Comment by gprezza** [comment]
Hi there!

Biopython was updated last month and I missed that Bio.Alphabet was removed; sorry for that.
I pushed a change that should fix your issue, please let me know how it goes.

**Comment by naphtap** [comment]
Thank you for the quick response, 
That problem seems to have been fixed, but now I come across this error. I tried checking position 11 in my fasta file and I don't see anything wrong with it, and I'm now wondering if it's my custom bed file that's the problem. That being said, it's formatted the same way as the example you provided.

Traceback (most recent call last):
  File "design_grnas.py", line 180, in <module>
    for line in _file:
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 11: invalid start byte

EDIT: I solved the error by using the --ma flag to lead it to my bed file, but it's asking for a BAM file instead.

**Comment by gprezza** [comment]
Whoops the error message is wrong and should say "bed" instead of bam, please just ignore that.

Would you mind attaching your bed file here so that I have a look at it?

**Comment by naphtap** [comment]
Here is my bed file: 

P749	703224	704764	16S_r01	.	+
P749	705223	708125	23S_r02	.	+
P749	708264	708385	5S_r03	.	+
P749	4886958	4887079	5S_r04	.	-
P749	4887219	4890111	23S_r05	.	-
P749	4890580	4892120	16S_r06	.	-
P749	5375023	5375144	5S_r07	.	-
P749	5375284	5378176	23S_r08	.	-
P749	5378645	5380185	16S_r09	.	-
P749	6151497	6151618	5S_r10	.	-
P749	6151758	6154637	23S_r11	.	-
P749	6155106	6156642	16S_r12	.	-

I'm wondering if it's possibly because the coordinates are wrong,

**Comment by gprezza** [comment]
Are the spaces between the columns tabs or spaces? They should be tabs, otherwise the file cannot be read properly. I'll add this somewhere in the description.

The coordinates shouldn't be a problem, as long as they are within the length of the genome.

**Comment by naphtap** [comment]
I double-checked the spaces between the columns and I can confirm that they are tabs

**Comment by gprezza** [comment]
Could you please attach the file by dragging it to the message box? I'll run the script myself and see what is going wrong.

Can you also post here the output of `grep ">" reference_sequences/*`?

**Comment by naphtap** [comment]
Hello, I have attached the input files into a zip file in this message.
[Troubleshoot_Files.zip](https://github.com/gprezza/DASH_rRNA_depletion/files/5416699/Troubleshoot_Files.zip)

Here also is the output of grep ">" reference_sequences/*:

"reference_sequences/genome_sequence.fa:>P749
Binary file reference_sequences/genome_sequence.fa matches
reference_sequences/P749.fasta:>P749"

**Comment by gprezza** [comment]
There was an issue caused by the fact that the script expected upper-case genome files.

Now it's fixed and I successfully run the script with your input files. Please let me know if it works for you as well!

**Comment by naphtap** [comment]
Thank you! It worked as intended!

**Comment by gprezza** [comment]
Thank you for the bug(s) report!
